### ISSUE TITLE
No metacity theme for Zukitre

### ISSUE THREAD

**Issue by imranmunshi** [lassekongo83/zuki-themes#112]
There is metacity theme in Zukitwo, but not in Zukitre, this makes it difficult to get a consistent look and feel if metacity is being used.

**Comment by lassekongo83** [comment]
Metacity (Marco) support has never been a priority. (I don't use MATE). The one from Zukitwo is a legacy one that I made before CSD was available. It's still there because it worked fine the last time I had the chance to test it. Not saying there won't be a Marco theme for Zukitre or Plano, but at the moment the priority is low. MATE users can however replace Marco with Xfwm4 which there is a theme for.

**Comment by fblais** [comment]
I'd like to add my vote to this wish!  :)
Or do you already have a similar metacity theme?
I use Zukitwo's one for the moment.
I use the Cinnamon DE by the way.
