### ISSUE TITLE
LibreOffice invisible check marks

### ISSUE THREAD

**Issue by questmark** [lassekongo83/zuki-themes#43]
All the checkmarks in the menus are invisible, until you hover/select the appropriate item.

Screenshots:
Zukitwo - invisible checkmarks:
http://s3.postimg.org/l3rrwixtf/zukitwo.png

Adwaita and Greybird - visible checkmarks:
http://s3.postimg.org/w231epmer/adwaita.png
http://s3.postimg.org/6ylyupos3/greybird.png

**Comment by wilfm** [comment]
I encountered this issue a while back, but probably didn't report it. As far as I remember it might also only be a Libreoffice issue, as I don't get it in Firefox or Gimp (I do get it in Libreoffice though):
![screenshot from 2015-05-18 10 44 26](https://cloud.githubusercontent.com/assets/6739839/7678435/f973ddc6-fd4b-11e4-86d0-c032eb1ae25f.png)

![screenshot from 2015-05-18 10 50 09](https://cloud.githubusercontent.com/assets/6739839/7678439/0591ef1c-fd4c-11e4-8890-984393a2ad43.png)

Most other apps I think use GTK3, which shows a radio button like thing instead of a tick anyway.

**Comment by questmark** [comment]
Now with the latest LibreOffice 5.0 it looks somewhat better. They're visible, but look rather bad. Better than nothing, I guess.

http://s29.postimg.org/i3sr457mv/2015_08_09_222541_1280x800_scrot.png

**Comment by ochosi** [comment]
Without having looked at Zuki's source, this is the commit that fixed it for Greybird: https://github.com/shimmerproject/Greybird/commit/42bc8ba7920169c11d4ac4ee47bc2181cc478366

**Comment by questmark** [comment]
Thanks you, that worked!

Zukitwo with the fix applied (LO with GTK2):
http://s13.postimg.org/lrusjzqgn/2015_08_10_084343_1280x800_scrot.png

Regarding that screenshot from my previous post and LO 5.0: it seems to use GTK3 now by default. That's why the check-marks looked different.

**Comment by lassekongo83** [comment]
Try the latest Zukitre build and see if the issue still exists. (New version of Zukitwo still in development.)
